### PR TITLE
Change target to dinput8

### PR DESCRIPTION
**Pull request by Silvris**
Current implementation of hid dll proxying (or there lack-of) breaks Linux compatibility, while properly proxying hid.dll causes double loading issues. As the final update to the game can use dinput8 for this purpose, it serves as a much better target.

Based this on my personal project for dinput8 proxying, adjust as you see fit.

### CODE REVIEW

**Comment by Dwyriel** [comment]
@Strackeror sorry to bother, but is there any plans for a new release implementing this change? I'm on linux and can't quite compile without going through some major headache (or installing windows just to do so).

**Comment by Strackeror** [comment]
There's a precompiled version tagged as a pre-release in the github releases, it should work as far as I know.

**Comment by Dwyriel** [comment]
Oh my bad, didn't check the whole release page, just the latest release. opsie.

Did some testing (mods linked at the end) and the loader itself seems to be working fine, but the "MonsterLoader.dll" and "QuestLoader.dll" that came packaged with the newer release were not loading, neither with the dinput8 loader or the older one I had (version 2.2.0), but the older versions of those plugins (that came with v2.2.0) worked fine with both loading methods (hid and dinput8).

If this is a problem specific to linux or not I can't tell, but looking through the changes made to those plugins since v2.2.0 (jun 4 2021) release I can't see how it would be. Specifically commits a16791dcbe6e105bd56309eece7dbd62611c661b and d8f207040a852cdebe6ec97ab2a1a6c5b16c5a9a.

logs:
[dinput8WithNewMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283716/dinput8WithNewMonster.QuestLoader.log)
[dinput8WithOldMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283717/dinput8WithOldMonster.QuestLoader.log)
[oldLoaderWithNewMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283718/oldLoaderWithNewMonster.QuestLoader.log)
[oldLoaderWithOldMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283719/oldLoaderWithOldMonster.QuestLoader.log)

mods:
[Bow Sticky Aim Removal](https://www.nexusmods.com/monsterhunterworld/mods/2580) (v1.2)
[Skippable Cutscenes](https://www.nexusmods.com/monsterhunterworld/mods/5540) (v1.1)
[Permanent Mon Arena Quest Pack](https://www.nexusmods.com/monsterhunterworld/mods/2172) (v1.0 lowest hp roll)
[Performance Booster and Plugin Extender](https://www.nexusmods.com/monsterhunterworld/mods/3473) (v1.7)

**Comment by Strackeror** [comment]
Hmm, okay, that's pretty weird. Currently I'm still fairly burnt out on world, so I'm not super motivated to do much testing, but when I eventually pick the game back up I'll try and see if I have similar issues.

**Comment by Isaiahmag** [comment]
> Oh my bad, didn't check the whole release page, just the latest release. opsie.
> 
> Did some testing (mods linked at the end) and the loader itself seems to be working fine, but the "MonsterLoader.dll" and "QuestLoader.dll" that came packaged with the newer release were not loading, neither with the dinput8 loader or the older one I had (version 2.2.0), but the older versions of those plugins (that came with v2.2.0) worked fine with both loading methods (hid and dinput8).
> 
> ~If this is a problem specific to linux or not I can't tell, but looking through the changes made to those plugins since v2.2.0 (jun 4 2021) release I can't see how it would be. Specifically commits [a16791d](https://github.com/Strackeror/MHW-QuestLoader/commit/a16791dcbe6e105bd56309eece7dbd62611c661b) and [d8f2070](https://github.com/Strackeror/MHW-QuestLoader/commit/d8f207040a852cdebe6ec97ab2a1a6c5b16c5a9a).~
> 
> ~Edit: just tested with Monster and Quest loader from version 2.2.1 that, as far as I know, contains the changes made in those commits and it works fine (tested w/ dinput8 loader). Whatever the problem is, it's related to something else.~
> 
> Edit2: Was able to compile from source and every .dll worked fine. The "MonsterLoader.dll" and "QuestLoader.dll" included in the release have different file sizes compared to the ones I compiled myself, which were closer to the ones I had before. Sadly my knowledge is very limited when it comes to windows stuff so I don't know if a readelf-like program exists, thus I couldn't compare the binaries myself. Still, whatever the problem is specific to those files included in the release, and not any of the code itself, either something happened during packaging of the .zip or during compilation.
> 
> logs: [dinput8WithNewMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283716/dinput8WithNewMonster.QuestLoader.log) [dinput8WithOldMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283717/dinput8WithOldMonster.QuestLoader.log) [oldLoaderWithNewMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283718/oldLoaderWithNewMonster.QuestLoader.log) [oldLoaderWithOldMonster&QuestLoader.log](https://github.com/Strackeror/MHW-QuestLoader/files/12283719/oldLoaderWithOldMonster.QuestLoader.log)
> 
> mods: [Bow Sticky Aim Removal](https://www.nexusmods.com/monsterhunterworld/mods/2580) (v1.2) [Skippable Cutscenes](https://www.nexusmods.com/monsterhunterworld/mods/5540) (v1.1) [Permanent Mon Arena Quest Pack](https://www.nexusmods.com/monsterhunterworld/mods/2172) (v1.0 lowest hp roll) [Performance Booster and Plugin Extender](https://www.nexusmods.com/monsterhunterworld/mods/3473) (v1.7)

How would one go about compiling the version that would work?

**Comment by Dwyriel** [comment]
@Isaiahmag You'll need a windows installation (I had to make a virtual windows machine for something else and took the opportunity to compile this as well), visual studio (not code), and msvc compiler v142 if I remember correctly. there might be a way to compile it under linux using mingw but it'd require a lot of work and might not even work as intended.

That said, you don't need to compile yourself, you can get the binaries from [this release](https://github.com/Strackeror/MHW-QuestLoader/releases/tag/v2.3.0), and substitute the included MonsterLoader.dll and QuestLoader.dll with the same files from v2.2.0 or v2.2.1 that you can get from nexusmods. Those 2 DLLs haven't changed between releases, only the modloader itself.

**Pull request merged**
